<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        employee detail page<br />
        <asp:MultiView ID="MultiView1" runat="server">
           
            <asp:View ID="View1" runat="server">
              
                <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="emp_id" DataSourceID="SqlDataSource3" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
                    <Columns>
                        <asp:BoundField DataField="emp_id" HeaderText="emp_id" ReadOnly="True" SortExpression="emp_id" />
                        <asp:BoundField DataField="emp_name" HeaderText="emp_name" SortExpression="emp_name" />
                        <asp:BoundField DataField="emp_salary" HeaderText="emp_salary" SortExpression="emp_salary" />
                        <asp:BoundField DataField="country" HeaderText="country" SortExpression="country" />
                    </Columns>
                    <SelectedRowStyle BackColor="#00FF99" BorderStyle="Dotted" />
                </asp:GridView>
                <br />
                <br />
            </asp:View>
         
            <asp:View ID="View2" runat="server">
                <asp:DetailsView ID="DetailsView1" runat="server" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" DataKeyNames="emp_id" DataSourceID="SqlDataSource2" Height="50px" Width="125px">
                    <Fields>
                        <asp:BoundField DataField="emp_id" HeaderText="emp_id" ReadOnly="True" SortExpression="emp_id" />
                        <asp:BoundField DataField="emp_name" HeaderText="emp_name" SortExpression="emp_name" />
                        <asp:BoundField DataField="emp_salary" HeaderText="emp_salary" SortExpression="emp_salary" />
                    </Fields>
                </asp:DetailsView>
                <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="show all employees" />
            </asp:View>
          
        </asp:MultiView>
       
        <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [emp] WHERE [emp_id] = @emp_id" InsertCommand="INSERT INTO [emp] ([emp_id], [emp_name], [emp_salary], [country]) VALUES (@emp_id, @emp_name, @emp_salary, @country)" SelectCommand="SELECT * FROM [emp]  where emp_id=@emp_id" UpdateCommand="UPDATE [emp] SET [emp_name] = @emp_name, [emp_salary] = @emp_salary, [country] = @country WHERE [emp_id] = @emp_id">
            <DeleteParameters>
                <asp:Parameter Name="emp_id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="emp_id" Type="Int32" />
                <asp:Parameter Name="emp_name" Type="String" />
                <asp:Parameter Name="emp_salary" Type="Int32" />
                <asp:Parameter Name="country" Type="String" />
            </InsertParameters>
            <SelectParameters>
                <asp:QueryStringParameter Name="emp_id" QueryStringField="userid" />
            </SelectParameters>
            <UpdateParameters>
                <asp:Parameter Name="emp_name" Type="String" />
                <asp:Parameter Name="emp_salary" Type="Int32" />
                <asp:Parameter Name="country" Type="String" />
                <asp:Parameter Name="emp_id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        <br />
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [emp] where emp_id=@emp_id">
            <SelectParameters>
                <asp:ControlParameter ControlID="GridView1" Name="emp_id" PropertyName="SelectedValue" />
            </SelectParameters>
        </asp:SqlDataSource>
        <br />
        <br />
        <br />
        <br />
    
    </div>
    </form>
</body>
</html>
